apiVersion: v2
name: aws-vpc-operator
version: 0.9.0-dev
appVersion: 0.9.0-dev
description: Operator for managing private AWS VPCs for Cluster API AWS workload clusters
home: https://github.com/giantswarm/aws-vpc-operator
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
annotations:
  application.giantswarm.io/team: phoenix
  io.giantswarm.application.team: phoenix
  config.giantswarm.io/version: 1.x.x
